## as priscribed in the assigmnent this function
## takes an matrix (square invertible) as input
## use `<<-` to assign a value to an object in an environment 
## different from the current environment. 
## and returns a list of functions set, get,SetMatinv,getMatinv

makeCacheMatrix <- function(x = matrix()) {
        
    Matinv = NULL
    set = function(y) {
 
        x <<- y
        Matinv <<- NULL
    }
    get = function() x
    setMatinv = function(inverse) Matinv <<- inverse 
    getMatinv = function() Matinv
    list(set=set, get=get, setMatinv=setMatinv, getMatinv=getMatinv)
    ##         this list is used as the input to cacheSolve()
}

## this is where teh inverse of the matrix is calculated using the solve() 
## function
## the cacheSolve function checks if the inverse has already been calculated or not
## input is a list of functions returned by the makeCacheMatrix()
cacheSolve <- function(x) 
{
    ## @x: output of makeCacheMatrix()
    ## return: inverse of the original matrix input to makeCacheMatrix()
    
    Matinv = x$getMatinv()
    
    # if the inverse has already been calculated
    if (!is.null(Matinv)){
        # get it from the cache and skips the computation. 
        message("getting cached data")
        return(Matinv)
    }
    
    # otherwise, calculates the inverse using the solve()
    myMat = x$get()
    Matinv = solve(myMat)
    
    # sets the value of the inverse in the cache via the setMatinv function.
    x$setMatinv(Matinv)
    Matinv
}






mymatrixinv<-function(mymatrix)
{
    mylist = makeCacheMatrix(mymatrix)
    BegTime= Sys.time()
    cacheSolve(mylist)
    ExecTime = Sys.time() - BegTime
    print(ExecTime)
    ExecTime = Sys.time() - BegTime
    cacheSolve(mylist)
    ExecTime = Sys.time() - BegTime
    print(ExecTime)
}


## setting the seed constant to make sure the same ramdom numbers
##generated by rnorm() are used by the  second call of cacheSolve()
## testing with twobytwo matrix first
set.seed(42)
twobytwo=c(4,3,3,2)
mymatrix=matrix(twobytwo, nrow=2, ncol=2)
mymatrixinv(mymatrix)
r=rnorm(1000000)
mymatrix=matrix(r, nrow=1000, ncol=1000)
mymatrixinv(mymatrix)


